import type { CourseId } from '../core/courses/progress.ts'
import type { CourseLanguage } from './courseUi.ts'
interface AdvancedExample { example:string; explanation:string; prompt:string; criteria:string[] }
const review = {
 de:['Ich habe die gefragten Inhalte ohne Vorlage abgerufen.','Ich habe alle Teile meiner Antwort mit dem neuen Beispiel verglichen und Fehler korrigiert.','Ich habe die Anwendung der Methode mit eigenen Worten erklärt.'],
 en:['I recalled the requested information without looking.','I compared every part of my answer with the new example and corrected errors.','I explained how I used the method in my own words.'],
 fr:['J’ai rappelé les informations demandées sans modèle.','J’ai comparé toutes les parties de ma réponse avec le nouvel exemple et corrigé les erreurs.','J’ai expliqué avec mes propres mots comment j’ai utilisé la méthode.'],
}
const examples: Record<CourseLanguage,Record<CourseId,[string,string,string]>> = {
 de:{
 'text-meaning':['Eine Bibliothek verlängert mittwochs ihre Öffnungszeit. Eine Befragung hatte gezeigt, dass viele Berufstätige erst abends kommen können. Für einen dreimonatigen Versuch verschiebt das Team deshalb Arbeitsstunden vom wenig besuchten Vormittag auf den Abend. Es erhält kein zusätzliches Personal. Die Bibliothek zählt die Besuche und sammelt Rückmeldungen. Danach entscheidet sie, ob die längere Öffnung den Bedarf deckt und mit der verfügbaren Arbeitszeit vereinbar ist.','Gliedere in Anlass, Maßnahme, Einschränkung und Überprüfung. Die längere Öffnung gilt zunächst nur mittwochs und nur versuchsweise.','Erkläre Anlass, Änderung, Grenze und Entscheidungskriterium. Welche Informationen würden fehlen, wenn du nur „Die Bibliothek öffnet länger“ sagst?'],
 'text-verbatim':['Vor dem Aufbruch prüfe ich die Karte. Dann packe ich Wasser und eine Jacke ein. An der Kreuzung wähle ich den linken Weg. Nach der Brücke mache ich eine kurze Pause.','Lerne zwei kleine Abschnitte. Verbinde „Jacke ein“ mit „An der Kreuzung“. Beginne zusätzlich einmal beim dritten Satz. Prüfe anschließend jedes Wort, nicht nur den Sinn.','Schreibe den ganzen Text wortgetreu. Vergleiche danach Wörter, Reihenfolge und Satzzeichen getrennt.'],
 'long-words':['Donaudampfschifffahrtsgesellschaft','Baue das Wort über Donau, Dampf, Schiff, Fahrt und Gesellschaft auf. Beachte das verbindende s vor Gesellschaft und die drei f in Schifffahrt. Bedeutungsbausteine helfen beim Aufbau; sie ersetzen nicht den Vergleich mit der vollständigen Schreibweise.','Schreibe das ganze Wort und erkläre seine Bedeutung. Prüfe danach besonders Schifffahrt und das verbindende s.'],
 'active-recall':['Warum beschlägt ein kaltes Glas in warmer, feuchter Luft? An der kalten Oberfläche kühlt die Luft ab; Wasserdampf kann dort zu flüssigen Tropfen kondensieren. Das Wasser stammt aus der Umgebungsluft, nicht aus dem Glasinneren.','Stelle zwei Fragen: Wie entstehen die Tropfen? Woher stammt das Wasser? Beantworte beide ohne Vorlage und korrigiere eine falsche Erklärung gezielt.','Erkläre die Tropfenbildung und die Herkunft des Wassers ohne Vorlage. Formuliere eine zusätzliche Frage, mit der du eine eigene Wissenslücke prüfen könntest.'],
 'spaced-practice':['Du kannst einen Begriff heute nur mit Hinweis erklären. Einen zweiten rufst du ohne Hilfe ab. Eine Woche später verwechselst du beim zweiten eine wichtige Einzelheit.','Vergleiche zwei Entscheidungen: Unsicheren Abruf zuerst klären und früher wieder aufgreifen; sicheren Abruf später erneut prüfen. Ein früherer Erfolg macht eine spätere Korrektur nicht überflüssig. Die App-Termine bleiben im vorhandenen Wiederholungssystem.','Beschreibe für beide Begriffe die nächste Lernhandlung. Erkläre, weshalb ein starres längeres Intervall trotz eines Fehlers nicht sinnvoll wäre.'],
 'meaningful-groups':['Brot, Socken, Käse, Zahnbürste, Hose, Seife, Apfel, Jacke, Handtuch','Ordne nach Lebensmitteln, Kleidung und Pflege. Rufe anschließend die einzelnen Gegenstände jeder Gruppe ab. Prüfe schließlich auch die ursprüngliche Reihenfolge: Kategorien speichern diese nicht automatisch.','Nenne alle neun Gegenstände mit ihren Gruppen. Erkläre, welche zusätzliche Verbindung du für die ursprüngliche Reihenfolge bräuchtest.'],
 'self-explanation':['Zwei gleiche Schalen enthalten gleich viel Wasser. Eine steht an einem warmen, luftigen Ort, die andere an einem kühleren Ort ohne Luftbewegung. Unter sonst gleichen Bedingungen verdunstet das Wasser im ersten Fall schneller.','Erkläre, was Wärme und der Abtransport feuchter Luft beitragen. Nenne die Bedingung „sonst gleich“, damit du aus diesem Beispiel keine Regel für beliebige unterschiedliche Gefäße machst.','Erkläre die Unterschiede mit eigenen Worten und nenne eine weitere Größe, die einen fairen Vergleich beeinflussen könnte.'],
 'story-method':['Buch → Tasse → Wolke → Leiter → Stern','Ein Buch klappt zu und katapultiert eine Tasse. Aus ihr steigt eine Wolke, die eine Leiter trägt. Die Leiter tippt einen Stern an. Jede Handlung verbindet zwei benachbarte Begriffe.','Rufe alle fünf Begriffe in der Reihenfolge ab. Beschreibe die Übergänge und verbessere einen, falls dir ein Begriff fehlt.'],
 'method-of-loci':['Haustür: ein Apfel klingelt. Flur: ein Hut rollt über den Boden. Küche: eine Uhr schwimmt im Spülbecken. Sofa: eine Kerze springt auf dem Kissen. Schreibtisch: ein Ballon hebt die Lampe an.','Gehe eine feste Route durch fünf unterscheidbare Orte. Lege je einen Begriff an einen Ort. Prüfe, ob du sowohl Ort als auch Begriff ohne Blick auf die Liste nennen kannst.','Gehe die Route im Kopf ab und nenne die fünf Begriffe. Beginne danach versuchsweise in der Küche und erkläre, wie du den Ort findest.'],
 'keyword-method':['Englisch: bell = Glocke; beach = Strand. Für bell kann ein bellender Hund an einer Glocke helfen; für beach ein „Biest“ am Strand als grobe deutsche Klangbrücke.','Klangbrücken müssen nicht exakt gleich klingen. Prüfe die tatsächliche englische Aussprache und Schreibweise unabhängig vom Bild. Für beide Wörter brauchst du ein Bild, das zur richtigen Bedeutung führt.','Nenne Wort und Bedeutung beider Paare. Erkläre die Bilder und weshalb du „beach“ nicht einfach wie das deutsche Schlüsselwort aussprichst.'],
 'number-images':['12 → Tanne; 21 → Note; 33 → Mama. In dieser vereinfachten Major-Zuordnung gilt t/d = 1, n = 2 und m = 3. Vokale tragen keine Ziffer.','Leite die Konsonantenlaute erst in Ziffern zurück: Tanne t-n, Note n-t, Mama m-m. Die Bilder helfen erst dann, wenn die Zuordnung sicher abrufbar ist.','Schreibe zu jedem Wort die Ziffernfolge und bilde die drei Wörter aus den Zahlen zurück. Erkläre einen Unterschied zwischen Bildhilfe und der zugrunde liegenden Zuordnung.'],
 'interleaved-practice':['Aufgabe A: die Hauptargumente eines Artikels erklären. Aufgabe B: einen kurzen Satz genau zitieren. Aufgabe C: die Reihenfolge von fünf Besorgungen behalten.','A verlangt Verständnis und Abruf der Kernaussagen; B zusätzlich Wortlautvergleich; C kann eine Geschichte oder feste Route unterstützen. Begründe die Wahl anhand des Lernziels.','Wähle für A, B und C jeweils eine passende Vorgehensweise. Nenne einen Grund, weshalb dieselbe Bildgeschichte nicht automatisch alle drei Ziele erfüllt.'],
 },
 en:{
 'text-meaning':['A library extends its Wednesday opening hours. A survey showed that many working people can only visit in the evening. For a three-month trial, staff therefore move working hours from a quiet morning to the evening. There are no additional staff. The library counts visits and collects feedback. It will then decide whether the longer opening meets demand and fits the available working hours.','Divide this into reason, action, constraint and evaluation. The extension applies only on Wednesdays and is initially a trial.','Explain the reason, change, constraint and decision criteria. What would be missing if you only said “The library opens longer”?'],
 'text-verbatim':['Before leaving, I check the map. Then I pack water and a jacket. At the junction, I take the left path. After the bridge, I take a short break.','Learn two short passages. Link “a jacket” to “At the junction”. Also practise starting at the third sentence. Then compare every word, not only the meaning.','Write the entire passage verbatim. Check words, order and punctuation separately.'],
 'long-words':['intercontinental','Use inter-, continent and -al to connect the spelling to the idea of something between continents. Meaningful parts are not necessarily the same as spoken syllables. Check the whole word after joining the parts.','Write the entire word and explain its meaning. Compare your spelling with the source, including the end of continent before -al.'],
 'active-recall':['Why does a cold glass mist up in warm, humid air? Air cools at the cold surface, where water vapour can condense into liquid droplets. The water comes from the surrounding air, not from inside the glass.','Ask two questions: How do the drops form? Where does the water come from? Answer both without looking and correct an incorrect explanation specifically.','Explain the formation and source of the droplets without looking. Add a question that would help you check a gap in your understanding.'],
 'spaced-practice':['Today you can explain one term only with a hint. You recall a second without help. A week later, you confuse an important detail of the second term.','Compare two decisions: clarify uncertain recall and revisit it sooner; check secure recall again later. Earlier success does not remove the need to correct a later error. App reminders remain in the existing review system.','Describe the next learning action for both terms. Explain why a fixed longer interval despite an error would be unhelpful.'],
 'meaningful-groups':['bread, socks, cheese, toothbrush, trousers, soap, apple, jacket, towel','Group into food, clothing and care items. Then recall the individual items in each group. Also check the original sequence: categories do not automatically preserve it.','Recall all nine items with their groups. Explain what additional links would preserve the original sequence.'],
 'self-explanation':['Two identical bowls contain equal amounts of water. One is in a warm, airy place; the other is cooler with still air. Other conditions being equal, water evaporates faster in the first case.','Explain the contribution of heat and the removal of humid air. Include “other conditions being equal” rather than turning this example into a claim about any two different containers.','Explain the difference in your own words and name another variable that could affect a fair comparison.'],
 'story-method':['book → cup → cloud → ladder → star','A book snaps shut and catapults a cup. A cloud rises from it, carrying a ladder. The ladder taps a star. Each action links two neighbouring items.','Recall all five items in order. Describe the links and improve one if an item is missing.'],
 'method-of-loci':['Front door: an apple rings the bell. Hall: a hat rolls along the floor. Kitchen: a clock floats in the sink. Sofa: a candle jumps on a cushion. Desk: a balloon lifts the lamp.','Walk a fixed route through five distinct places. Put one item at each place. Check whether you can name both the place and the item without looking at the list.','Walk the route mentally and recall all five items. Then try starting in the kitchen and explain how you find that location.'],
 'keyword-method':['Spanish: mesa = table; pato = duck. Imagine a mess on a table for mesa, and someone patting a duck for pato.','The English keywords are approximate sound cues. Check actual Spanish pronunciation and spelling separately. Each image must lead to the correct meaning.','Recall the Spanish word and meaning of both pairs. Explain the images and why you should not pronounce the Spanish words exactly like the English cues.'],
 'number-images':['12 → tin; 21 → net; 33 → mime. In this simplified Major mapping, t/d = 1, n = 2 and m = 3. Vowels carry no digit.','Convert consonant sounds back to digits first: tin t-n, net n-t, mime m-m. Images help only after the mapping is retrievable.','Write the number for each word and retrieve the words from the numbers. Explain the difference between an image aid and its underlying mapping.'],
 'interleaved-practice':['Task A: explain an article’s main arguments. Task B: quote a short sentence exactly. Task C: remember the order of five errands.','A needs understanding and retrieval of main points; B also needs word-for-word comparison; C may benefit from a story or fixed route. Justify your choice using the learning goal.','Choose an approach for A, B and C. Explain why one picture story does not automatically achieve all three goals.'],
 },
 fr:{
 'text-meaning':['Une bibliothèque prolonge son ouverture le mercredi. Une enquête a montré que beaucoup de personnes qui travaillent ne peuvent venir que le soir. Pour un essai de trois mois, l’équipe déplace donc des heures de travail d’une matinée peu fréquentée vers le soir. Aucun personnel supplémentaire n’est prévu. La bibliothèque compte les visites et recueille les avis. Elle décidera ensuite si cette ouverture répond au besoin et reste compatible avec les heures de travail disponibles.','Distingue raison, mesure, contrainte et évaluation. L’ouverture prolongée concerne seulement le mercredi et constitue d’abord un essai.','Explique la raison, le changement, la contrainte et les critères de décision. Que manquerait-il si tu disais seulement « La bibliothèque ouvre plus longtemps » ?'],
 'text-verbatim':['Avant de partir, je vérifie la carte. Puis je prends de l’eau et une veste. Au carrefour, je choisis le chemin de gauche. Après le pont, je fais une courte pause.','Apprends deux petits passages. Relie « une veste » à « Au carrefour ». Entraîne-toi aussi à commencer par la troisième phrase. Vérifie ensuite chaque mot, pas seulement le sens.','Écris tout le passage mot pour mot. Vérifie séparément les mots, leur ordre et la ponctuation.'],
 'long-words':['anticonstitutionnellement','Relie anti- à l’idée d’opposition et constitutionnel à la constitution. La terminaison -ment forme ici un adverbe ; observe attentivement la forme complète avec -nellement. Les éléments de sens ne sont pas forcément des syllabes.','Écris le mot entier et explique son sens. Compare ensuite toute l’orthographe avec le modèle, notamment -nellement.'],
 'active-recall':['Pourquoi un verre froid se couvre-t-il de buée dans un air chaud et humide ? L’air se refroidit près de la surface froide ; la vapeur d’eau peut y former des gouttelettes liquides par condensation. Cette eau vient de l’air ambiant, pas de l’intérieur du verre.','Pose deux questions : comment les gouttes se forment-elles ? D’où vient l’eau ? Réponds sans regarder puis corrige précisément une explication erronée.','Explique la formation et l’origine des gouttes sans modèle. Ajoute une question qui permettrait de vérifier une lacune dans ta compréhension.'],
 'spaced-practice':['Aujourd’hui, tu ne peux expliquer un terme qu’avec un indice. Tu en retrouves un deuxième sans aide. Une semaine plus tard, tu confonds un détail important du deuxième terme.','Compare deux décisions : clarifier un rappel incertain et le reprendre plus tôt ; vérifier plus tard un rappel sûr. Un succès ancien ne dispense pas de corriger une erreur récente. Les rappels de l’app restent gérés par le système existant.','Décris la prochaine action d’apprentissage pour les deux termes. Explique pourquoi allonger systématiquement l’intervalle malgré une erreur serait peu utile.'],
 'meaningful-groups':['pain, chaussettes, fromage, brosse à dents, pantalon, savon, pomme, veste, serviette','Regroupe les aliments, les vêtements et les objets de toilette. Retrouve ensuite chaque objet de chaque groupe. Vérifie aussi l’ordre initial : les catégories ne le conservent pas automatiquement.','Retrouve les neuf objets avec leurs groupes. Explique quels liens supplémentaires aideraient à conserver l’ordre initial.'],
 'self-explanation':['Deux bols identiques contiennent la même quantité d’eau. L’un se trouve dans un endroit chaud et aéré, l’autre dans un endroit plus frais sans mouvement d’air. Toutes choses égales par ailleurs, l’eau s’évapore plus vite dans le premier cas.','Explique le rôle de la chaleur et de l’évacuation de l’air humide. Précise « toutes choses égales par ailleurs », sans généraliser à deux récipients quelconques.','Explique la différence avec tes propres mots et cite une autre variable qui pourrait influencer une comparaison équitable.'],
 'story-method':['livre → tasse → nuage → échelle → étoile','Un livre se referme et catapulte une tasse. Un nuage en sort en portant une échelle. L’échelle touche une étoile. Chaque action relie deux éléments voisins.','Retrouve les cinq éléments dans l’ordre. Décris les liens et améliore-en un si un élément manque.'],
 'method-of-loci':['Porte d’entrée : une pomme sonne. Couloir : un chapeau roule sur le sol. Cuisine : une horloge flotte dans l’évier. Canapé : une bougie saute sur un coussin. Bureau : un ballon soulève la lampe.','Suis un trajet fixe passant par cinq lieux distincts. Place un élément à chaque endroit. Vérifie si tu retrouves le lieu et l’élément sans regarder la liste.','Parcours mentalement le trajet et retrouve les cinq éléments. Essaie ensuite de commencer dans la cuisine et explique comment tu retrouves cet endroit.'],
 'keyword-method':['Anglais : bell = cloche ; beach = plage. Imagine une belle cloche pour bell et une biche sur une plage pour beach.','Les mots français sont des indices sonores approximatifs. Vérifie séparément la prononciation anglaise réelle et l’orthographe. Chaque image doit conduire au bon sens.','Retrouve le mot anglais et le sens des deux paires. Explique les images et pourquoi les indices français ne remplacent pas la prononciation anglaise.'],
 'number-images':['12 → tonne ; 21 → natte ; 33 → momie. Dans ce système majeur simplifié, t/d = 1, n = 2 et m = 3. Les voyelles ne portent pas de chiffre.','Retrouve d’abord les chiffres à partir des sons consonantiques : tonne t-n, natte n-t, momie m-m. Les images sont utiles lorsque ces correspondances sont accessibles en mémoire.','Écris les chiffres correspondant à chaque mot puis retrouve les mots à partir des nombres. Explique la différence entre l’image et le code qui la soutient.'],
 'interleaved-practice':['Tâche A : expliquer les arguments principaux d’un article. Tâche B : citer exactement une courte phrase. Tâche C : retenir l’ordre de cinq courses à faire.','A demande compréhension et rappel des idées ; B exige aussi une comparaison mot pour mot ; C peut être aidée par une histoire ou un trajet fixe. Justifie le choix par l’objectif.','Choisis une approche pour A, B et C. Explique pourquoi une même histoire imagée ne remplit pas automatiquement les trois objectifs.'],
 },
}
export function advancedExample(locale:CourseLanguage,id:CourseId):AdvancedExample {
 const [example,explanation,prompt]=examples[locale][id]
 return {example,explanation,prompt,criteria:review[locale]}
}
