import { expect, test } from '@playwright/test'
import { openPage, visit } from './helpers.ts'

test('course hides the source, requires review and retains completion after reload', async ({ page }) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Lange Wörter sicher behalten', exact:true}).click()
  await expect(page.getByText('Was ist das und wozu dient es?')).toBeVisible()
  await expect(page.locator('.course-lesson blockquote')).toHaveText('Krankenversicherungsbeitrag')
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveCount(0)
  await expect(page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true})).toBeDisabled()
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Krankenversicherungsbeitrag')
  await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
  await expect(page.getByRole('button', {name:'Übung abschließen',exact:true})).toBeDisabled()
  for (const checkbox of await page.locator('.course-check input').all()) await checkbox.check()
  await page.getByRole('button', {name:'Übung abschließen',exact:true}).click()
  await expect(page.getByText('Übung durchgeführt und gespeichert.', {exact:true})).toBeVisible()
  await page.reload()
  await openPage(page, 'Lernkurse')
  await expect(page.getByText('1 von 5 Übungen durchgeführt', {exact:true})).toBeVisible()
})

test('own text is hidden during recall and discarded when leaving the course', async ({ page }) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Lange Texte inhaltlich behalten',exact:true}).click()
  await page.getByText('Mit eigenem Material üben', {exact:true}).click()
  await page.getByLabel('Eigenes Material statt Beispiel verwenden', {exact:true}).check()
  await expect(page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true})).toBeDisabled()
  await page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)', {exact:true}).fill('Meine private Probe über rote Schiffe.')
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await expect(page.getByText('Meine private Probe über rote Schiffe.', {exact:true})).toHaveCount(0)
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Rote Schiffe')
  await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveText('Meine private Probe über rote Schiffe.')
  await expect(page.getByText('Die wesentlichen Aussagen sind enthalten.', {exact:true})).toBeVisible()
  await page.getByRole('button', {name:'Zur Kursübersicht',exact:true}).click()
  await page.getByRole('button', {name:'Kurs öffnen : Lange Texte inhaltlich behalten',exact:true}).click()
  await page.getByText('Mit eigenem Material üben', {exact:true}).click()
  await expect(page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)', {exact:true})).toHaveValue('')
})

test('downloaded app can open an unvisited reading course offline', async ({ page, context }) => {
  await visit(page)
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise<void>(resolve => navigator.serviceWorker.addEventListener('controllerchange', () => resolve(), {once:true}))
  })
  await context.setOffline(true)
  await page.reload()
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Texte wortgetreu lernen',exact:true}).click()
  await expect(page.getByText('Am Morgen öffne ich das Fenster. Frische Luft strömt ins Zimmer. Danach beginne ich meinen Tag.', {exact:true})).toBeVisible()
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await expect(page.getByLabel('Deine Antwort', {exact:true})).toBeVisible()
  await context.setOffline(false)
})

test('active recall uses criteria for the learner’s own material', async ({ page }) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Aktives Abrufen',exact:true}).click()
  await page.getByText('Mit eigenem Material üben', {exact:true}).click()
  await page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)', {exact:true}).fill('Frage: Wie viele Seiten hat ein Dreieck? Antwort: Drei.')
  await page.getByLabel('Eigenes Material statt Beispiel verwenden', {exact:true}).check()
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Drei Seiten')
  await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
  await expect(page.getByText('Ich habe eine klare Frage zu meinem Material gestellt.', {exact:true})).toBeVisible()
  await expect(page.getByText('Meine Antwort nennt, dass Verdunsten Energie benötigt.', {exact:true})).toHaveCount(0)
  await page.getByRole('button', {name:'Erneut ohne Vorlage abrufen',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveCount(0)
  await expect(page.getByLabel('Deine Antwort', {exact:true})).toHaveValue('')
})

test('English spaced practice explains the existing schedule without promising new cards', async ({ page }) => {
  await visit(page)
  await page.getByRole('combobox', {name:'Sprache',exact:true}).selectOption('en')
  await openPage(page, 'Learning courses')
  await page.getByRole('button', {name:'Open course : Spaced practice',exact:true}).click()
  await expect(page.getByText('What is it for?', {exact:true})).toBeVisible()
  await expect(page.getByText('Practise with your own material', {exact:true})).toHaveCount(0)
  await page.getByRole('button', {name:'Hide source and practise',exact:true}).click()
  await page.getByLabel('Your answer', {exact:true}).fill('Retrieve before checking. Correct the gap and shorten the next interval. Increase it after reliable retrieval.')
  await page.getByRole('button', {name:'Compare with the source',exact:true}).click()
  for (const checkbox of await page.locator('.course-check input').all()) await checkbox.check()
  await page.getByRole('button', {name:'Complete exercise',exact:true}).click()
  await expect(page.getByText(/Completing this reading course does not create new review cards/)).toBeVisible()
})
