import { expect, test } from '@playwright/test'
import { leavePage, openPage, visit } from './helpers.ts'

test('course hides the source, requires review and retains completion after reload', async ({ page }) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Lange Wörter sicher behalten', exact:true}).click()
  await expect(page.getByText('Was ist das und wozu dient es?')).toBeVisible()
  await expect(page.locator('.course-lesson blockquote')).toHaveText('Krankenversicherungsbeitrag')
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveCount(0)
  await expect(page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true})).toBeDisabled()
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Krankenversicherungsbeitrag')
  await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
  await expect(page.getByRole('button', {name:'Übung abschließen',exact:true})).toBeDisabled()
  for (const checkbox of await page.locator('.course-check input').all()) await checkbox.check()
  await page.getByRole('button', {name:'Übung abschließen',exact:true}).click()
  await expect(page.getByText('Übung durchgeführt und gespeichert.', {exact:true})).toBeVisible()
  await page.reload()
  await openPage(page, 'Lernkurse')
  await expect(page.getByText('1 von 12 Übungen durchgeführt', {exact:true})).toBeVisible()
})

test('own text is hidden during recall and discarded when leaving the course', async ({ page }) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Lange Texte inhaltlich behalten',exact:true}).click()
  await page.getByText('Mit eigenem Material üben', {exact:true}).click()
  await page.getByLabel('Eigenes Material statt Beispiel verwenden', {exact:true}).check()
  await expect(page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true})).toBeDisabled()
  await page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)', {exact:true}).fill('Meine private Probe über rote Schiffe.')
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await expect(page.getByText('Meine private Probe über rote Schiffe.', {exact:true})).toHaveCount(0)
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Rote Schiffe')
  await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveText('Meine private Probe über rote Schiffe.')
  await expect(page.getByText('Die wesentlichen Aussagen sind enthalten.', {exact:true})).toBeVisible()
  await page.getByRole('button', {name:'Zur Kursübersicht',exact:true}).click()
  await page.getByRole('button', {name:'Kurs öffnen : Lange Texte inhaltlich behalten',exact:true}).click()
  await page.getByText('Mit eigenem Material üben', {exact:true}).click()
  await expect(page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)', {exact:true})).toHaveValue('')
})

test('downloaded app can open an unvisited reading course offline', async ({ page, context }) => {
  await visit(page)
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise<void>(resolve => navigator.serviceWorker.addEventListener('controllerchange', () => resolve(), {once:true}))
  })
  await context.setOffline(true)
  await page.reload()
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Texte wortgetreu lernen',exact:true}).click()
  await expect(page.getByText('Am Morgen öffne ich das Fenster. Frische Luft strömt ins Zimmer. Danach beginne ich meinen Tag.', {exact:true})).toBeVisible()
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await expect(page.getByLabel('Deine Antwort', {exact:true})).toBeVisible()
  await context.setOffline(false)
})

test('active recall uses criteria for the learner’s own material', async ({ page }) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Aktives Abrufen',exact:true}).click()
  await page.getByText('Mit eigenem Material üben', {exact:true}).click()
  await page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)', {exact:true}).fill('Frage: Wie viele Seiten hat ein Dreieck? Antwort: Drei.')
  await page.getByLabel('Eigenes Material statt Beispiel verwenden', {exact:true}).check()
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Drei Seiten')
  await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
  await expect(page.getByText('Ich habe eine klare Frage zu meinem Material gestellt.', {exact:true})).toBeVisible()
  await expect(page.getByText('Meine Antwort nennt, dass Verdunsten Energie benötigt.', {exact:true})).toHaveCount(0)
  await page.getByRole('button', {name:'Erneut ohne Vorlage abrufen',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveCount(0)
  await expect(page.getByLabel('Deine Antwort', {exact:true})).toHaveValue('')
})

test('English spaced practice explains the existing schedule without promising new cards', async ({ page }) => {
  await visit(page)
  await page.getByRole('combobox', {name:'Sprache',exact:true}).selectOption('en')
  await openPage(page, 'Learning courses')
  await page.getByRole('button', {name:'Open course : Spaced practice',exact:true}).click()
  await expect(page.getByText('What is it for?', {exact:true})).toBeVisible()
  await expect(page.getByText('Practise with your own material', {exact:true})).toHaveCount(0)
  await page.getByRole('button', {name:'Hide source and practise',exact:true}).click()
  await page.getByLabel('Your answer', {exact:true}).fill('Retrieve before checking. Correct the gap and shorten the next interval. Increase it after reliable retrieval.')
  await page.getByRole('button', {name:'Compare with the source',exact:true}).click()
  for (const checkbox of await page.locator('.course-check input').all()) await checkbox.check()
  await page.getByRole('button', {name:'Complete exercise',exact:true}).click()
  await expect(page.getByText(/Completing this reading course does not create new review cards/)).toBeVisible()
})

test('grouping requires recall of the items, not only headings', async ({ page }) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Sinnvolle Einheiten bilden',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toContainText('Apfel · Hammer · Hemd')
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveCount(0)
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Obst: Apfel, Birne, Banane. Werkzeug: Hammer, Säge, Zange. Kleidung: Hemd, Jacke, Hose.')
  await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
  await expect(page.getByText('Ich habe alle neun Begriffe mit der Vorlage abgeglichen und fehlende oder zusätzliche Begriffe korrigiert.', {exact:true})).toBeVisible()
  await expect(page.getByRole('button', {name:'Übung abschließen',exact:true})).toBeDisabled()
})

test('self explanation offers an example and appropriate checks for personal material', async ({ page }) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Zusammenhänge selbst erklären',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toContainText('3/4 = 6/8')
  await page.getByText('Mit eigenem Material üben', {exact:true}).click()
  await page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)', {exact:true}).fill('Eine Begründung aus meinem Lernstoff.')
  await page.getByLabel('Eigenes Material statt Beispiel verwenden', {exact:true}).check()
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Meine Erklärung und ein ähnliches Beispiel.')
  await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
  await expect(page.getByText('Ich habe eine Warum- oder Wie-Frage zu meinem Material beantwortet.', {exact:true})).toBeVisible()
  await expect(page.getByText('Ich erkläre, dass jedes gleich große Teil noch einmal halbiert wird.', {exact:true})).toHaveCount(0)
})

for (const [title, example] of [
  ['Begriffe durch Geschichten verbinden', 'Schlüssel → Zitrone → Fahrrad'],
  ['Orte als Gedächtnisstützen nutzen', 'Beispielweg: Haustür'],
  ['Neue Vokabeln mit Schlüsselwörtern verbinden', 'Englisch: bell = Glocke'],
  ['Zahlen in Bilder übersetzen', '1 → t/d; 2 → n'],
  ['Passende Vorgehensweisen unterscheiden', 'Rechteck: Fläche'],
]) {
  test(`additional method ${title} hides its worked example before recall`, async ({ page }) => {
    await visit(page)
    await openPage(page, 'Lernkurse')
    await page.getByRole('button', {name:`Kurs öffnen : ${title}`,exact:true}).click()
    await expect(page.locator('.course-lesson blockquote')).toContainText(example)
    await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
    await expect(page.locator('.course-lesson blockquote')).toHaveCount(0)
    await page.getByLabel('Deine Antwort', {exact:true}).fill('Mein eigener Abrufversuch')
    await page.getByRole('button', {name:'Mit der Vorlage vergleichen',exact:true}).click()
    await expect(page.locator('.course-lesson blockquote')).toContainText(example)
    await expect(page.locator('.course-check')).toHaveCount(3)
    await expect(page.getByRole('button', {name:'Übung abschließen',exact:true})).toBeDisabled()
  })
}

test('French course content and controls work offline and share progress with German', async ({ page, context }) => {
  await visit(page)
  await page.getByRole('combobox', {name:'Sprache',exact:true}).selectOption('fr')
  // Let the selected language take effect before the offline document restart.
  await openPage(page, 'Cours d’apprentissage')
  await expect(page.locator('.courses')).toHaveAttribute('lang','fr')
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise<void>(resolve => navigator.serviceWorker.addEventListener('controllerchange', () => resolve(), {once:true}))
  })
  await context.setOffline(true)
  await page.reload()
  await openPage(page, 'Cours d’apprentissage')
  await expect(page.locator('.courses')).toHaveAttribute('lang','fr')
  await page.getByRole('button', {name:'Ouvrir le cours : Retenir les mots longs',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveText('incompréhensible')
  await page.getByRole('button', {name:'Masquer le modèle et s’entraîner',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toHaveCount(0)
  await page.getByLabel('Ta réponse', {exact:true}).fill('incompréhensible')
  await page.getByRole('button', {name:'Comparer avec le modèle',exact:true}).click()
  for (const checkbox of await page.locator('.course-check input').all()) await checkbox.check()
  await page.getByRole('button', {name:'Terminer l’exercice',exact:true}).click()
  await expect(page.getByText('Exercice effectué et progression enregistrée.', {exact:true})).toBeVisible()
  await context.setOffline(false)
  await page.reload()
  await page.getByRole('combobox', {name:'Language',exact:true}).selectOption('de')
  await openPage(page, 'Lernkurse')
  await expect(page.getByText('1 von 12 Übungen durchgeführt', {exact:true})).toBeVisible()
})

test('French personal-text criteria never use the example’s factual answers', async ({ page }) => {
  await visit(page)
  await page.getByRole('combobox', {name:'Sprache',exact:true}).selectOption('fr')
  await openPage(page, 'Cours d’apprentissage')
  await page.getByRole('button', {name:'Ouvrir le cours : Retenir le sens d’un texte long',exact:true}).click()
  await page.getByText('S’entraîner avec son propre contenu', {exact:true}).click()
  await page.getByLabel('Ton texte ou ton mot (pour cet essai uniquement)', {exact:true}).fill('Mon texte personnel sur un bateau.')
  await page.getByLabel('Utiliser mon contenu à la place de l’exemple', {exact:true}).check()
  await page.getByRole('button', {name:'Masquer le modèle et s’entraîner',exact:true}).click()
  await page.getByLabel('Ta réponse', {exact:true}).fill('Un bateau')
  await page.getByRole('button', {name:'Comparer avec le modèle',exact:true}).click()
  await expect(page.getByText('Les idées essentielles sont présentes.', {exact:true})).toBeVisible()
  await expect(page.getByText('J’ai indiqué que des arbres sont plantés le long de la route.', {exact:true})).toHaveCount(0)
})

test('coach choices persist and changing assignment preserves a recall answer', async ({page}) => {
  await visit(page)
  await openPage(page, 'Lernkurse')
  await page.getByRole('button', {name:'Kurs öffnen : Lange Wörter sicher behalten',exact:true}).click()
  await expect(page.locator('.course-coach-current img')).toHaveAttribute('src','/coaches/original.webp')
  await page.getByRole('button', {name:'Vorlage ausblenden und üben',exact:true}).click()
  await page.getByLabel('Deine Antwort', {exact:true}).fill('Meine Antwort bleibt bestehen')
  await page.locator('.course-coaches summary').click()
  await page.locator('#course-coach-mode').selectOption('global')
  await expect(page.getByText('Coach-Auswahl gespeichert.',{exact:true})).toBeVisible()
  await page.locator('#course-coach-all').selectOption('lin')
  await expect(page.getByText('Coach-Auswahl gespeichert.',{exact:true})).toBeVisible()
  await expect(page.locator('.course-coach-current img')).toHaveAttribute('src','/coaches/lin.webp')
  await expect(page.getByLabel('Deine Antwort', {exact:true})).toHaveValue('Meine Antwort bleibt bestehen')
  await page.reload()
  await page.getByRole('combobox',{name:'Sprache',exact:true}).selectOption('fr')
  await openPage(page, 'Cours d’apprentissage')
  await page.locator('.course-coaches summary').click()
  await expect(page.locator('#course-coach-mode')).toHaveValue('global')
  await expect(page.locator('#course-coach-all')).toHaveValue('lin')
  await page.locator('#course-coach-mode').selectOption('custom')
  await expect(page.getByText('Choix du coach enregistré.',{exact:true})).toBeVisible()
  await page.locator('#course-coach-long-words').selectOption('rafael')
  await expect(page.getByText('Choix du coach enregistré.',{exact:true})).toBeVisible()
  await expect(page.locator('#course-coach-story-method')).toHaveValue('default')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.reload()
  await openPage(page, 'Cours d’apprentissage')
  await page.locator('.course-coaches summary').click()
  await expect(page.locator('#course-coach-long-words')).toHaveValue('rafael')
})

test('all coach portraits load offline without external image requests', async ({page,context}) => {
  await visit(page)
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise<void>(resolve=>navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true}))
  })
  const externalImages: string[] = []
  page.on('request',request=>{
    if (request.resourceType()==='image' && new URL(request.url()).origin!==new URL(page.url()).origin) externalImages.push(request.url())
  })
  await context.setOffline(true)
  await page.reload()
  await openPage(page, 'Lernkurse')
  await page.locator('.course-coaches summary').click()
  const images = page.locator('.course-coach-gallery img')
  await expect(images).toHaveCount(3)
  for (const image of await images.all()) {
    await image.scrollIntoViewIfNeeded()
    await expect.poll(()=>image.evaluate(img=>(img as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  }
  expect(new Set(await images.evaluateAll(imgs=>imgs.map(img=>img.getAttribute('src')))).size).toBe(3)
  expect(externalImages).toEqual([])
  await context.setOffline(false)
})

test('story narration has independent language, persistent speed and the same recall exercise', async ({page})=>{
  test.setTimeout(60_000) // Three local audio loads plus a persisted exercise and reload.
  await visit(page)
  await page.getByRole('combobox',{name:'Sprache',exact:true}).selectOption('es')
  await openPage(page,'Learning courses')
  await page.getByRole('button',{name:'Open course : Connect items through stories',exact:true}).click()
  await page.getByRole('button',{name:'Listen and watch',exact:true}).click()
  const audio=page.locator('.course-media audio')
  await expect(audio).toHaveAttribute('src','/course-media/story/en.m4a')
  await expect(page.locator('.course-caption')).toHaveAttribute('lang','es')
  await page.locator('#course-audio-language').selectOption('fr')
  await expect(audio).toHaveAttribute('src','/course-media/story/fr.m4a')
  await expect(page.locator('.course-caption')).toHaveAttribute('lang','es')
  await page.locator('#course-speed').selectOption('1.5')
  await expect(page.locator('#course-speed')).toBeEnabled()
  await audio.evaluate((element:HTMLAudioElement)=>element.load())
  await expect.poll(()=>audio.evaluate((element:HTMLAudioElement)=>element.readyState)).toBeGreaterThan(0)
  expect(await audio.evaluate((element:HTMLAudioElement)=>element.playbackRate)).toBe(1.5)
  expect(await audio.evaluate((element:HTMLAudioElement)=>element.paused)).toBe(true)
  await page.getByRole('button',{name:'Read only',exact:true}).click()
  await expect(audio).toHaveCount(0)
  await page.getByRole('button',{name:'Listen and watch',exact:true}).click()
  await audio.evaluate((element:HTMLAudioElement)=>element.load())
  await expect.poll(()=>audio.evaluate((element:HTMLAudioElement)=>element.readyState)).toBeGreaterThan(0)
  await expect.poll(()=>audio.evaluate((element:HTMLAudioElement)=>element.seekable.length ? element.seekable.end(0) : 0)).toBeGreaterThan(60)
  // Seeking past the solution boundary must enter recall rather than reveal it.
  await audio.evaluate((element:HTMLAudioElement)=>{element.currentTime=element.duration-1})
  await expect(page.getByLabel('Your answer',{exact:true})).toBeVisible()
  await expect(audio).toHaveCount(0)
  await expect(page.locator('.course-lesson blockquote')).toHaveCount(0)
  await expect(page.locator('.course-media details')).toHaveCount(0)
  await page.getByLabel('Your answer',{exact:true}).fill('Key, lemon, bicycle')
  await page.getByRole('button',{name:'Compare with the source',exact:true}).click()
  await expect(page.locator('.course-lesson blockquote')).toBeVisible()
  for(const checkbox of await page.locator('.course-check input').all())await checkbox.check()
  await page.getByRole('button',{name:'Complete exercise',exact:true}).click()
  await expect(page.getByText('Exercise practised and saved.',{exact:true})).toBeVisible()
  await page.reload()
  await openPage(page,'Learning courses')
  await expect(page.getByText('1 of 12 exercises practised',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Open course : Connect items through stories',exact:true}).click()
  await expect(page.getByRole('button',{name:'Read only',exact:true})).toBeVisible()
  await expect(page.locator('#course-audio-language')).toHaveValue('fr')
  await expect(page.locator('#course-speed')).toHaveValue('1.5')
})

test('all three story audio tracks are cached offline and no external media is required',async({page,context})=>{
  test.setTimeout(60_000) // Wait for complete offline installation and decode all three tracks.
  await visit(page)
  await page.evaluate(async()=>{
    await navigator.serviceWorker.ready
    if(!navigator.serviceWorker.controller)await new Promise<void>(resolve=>navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true}))
  })
  await context.setOffline(true)
  await page.reload()
  await openPage(page,'Lernkurse')
  await page.getByRole('button',{name:'Kurs öffnen : Begriffe durch Geschichten verbinden',exact:true}).click()
  await page.getByRole('button',{name:'Anhören und ansehen',exact:true}).click()
  for(const language of ['de','en','fr']){
    await page.locator('#course-audio-language').selectOption(language)
    await expect(page.locator('#course-audio-language')).toBeEnabled()
    const audio=page.locator('.course-media audio')
    await audio.evaluate((element:HTMLAudioElement)=>element.load())
    await expect.poll(()=>audio.evaluate((element:HTMLAudioElement)=>element.readyState)).toBeGreaterThan(0)
    expect(await audio.evaluate((element:HTMLAudioElement)=>element.duration)).toBeGreaterThan(60)
    expect(await audio.evaluate((element:HTMLAudioElement)=>new URL(element.currentSrc).origin===location.origin)).toBe(true)
  }
  const range=await page.evaluate(async()=>{const response=await fetch('/course-media/story/fr.m4a',{headers:{Range:'bytes=100-199'}});return {status:response.status,size:(await response.arrayBuffer()).byteLength,range:response.headers.get('Content-Range')}})
  expect(range.status).toBe(206)
  expect(range.size).toBe(100)
  expect(range.range).toMatch(/^bytes 100-199\/\d+$/)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await context.setOffline(false)
})


test('course stages unlock progressively and course XP cannot be farmed',async({page})=>{
  test.setTimeout(60_000)
  await visit(page)
  await openPage(page,'Lernkurse')
  await page.getByRole('button',{name:'Kurs öffnen : Lange Wörter sicher behalten',exact:true}).click()
  await expect(page.locator('#course-stage option[value="2"]')).toBeDisabled()
  await expect(page.locator('#course-stage option[value="3"]')).toBeDisabled()
  async function complete(answer:string){
    await page.getByRole('button',{name:'Vorlage ausblenden und üben',exact:true}).click()
    await page.getByLabel('Deine Antwort',{exact:true}).fill(answer)
    await page.getByRole('button',{name:'Mit der Vorlage vergleichen',exact:true}).click()
    for(const checkbox of await page.locator('.course-check input').all())await checkbox.check()
    await page.getByRole('button',{name:'Übung abschließen',exact:true}).click()
    await expect(page.getByText('Übung durchgeführt und gespeichert.',{exact:true})).toBeVisible()
  }
  await complete('Krankenversicherungsbeitrag')
  await page.locator('#course-stage').selectOption('2')
  await expect(page.locator('.course-lesson blockquote')).toHaveText('Donaudampfschifffahrtsgesellschaft')
  await complete('Donaudampfschifffahrtsgesellschaft: Gesellschaft für Dampfschifffahrt auf der Donau.')
  await page.locator('#course-stage').selectOption('3')
  await expect(page.getByRole('button',{name:'Vorlage ausblenden und üben',exact:true})).toBeDisabled()
  await page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)',{exact:true}).fill('Frage: Wie schreibe ich mein Wort? Vorlage: Sonnenblumenkern.')
  await complete('Sonnenblumenkern: Sonnenblume und Kern.')
  await leavePage(page)
  await expect(page.locator('.journey-xp')).toContainText('10 XP')
  await page.reload()
  await openPage(page,'Lernkurse')
  await page.getByRole('button',{name:'Kurs öffnen : Lange Wörter sicher behalten',exact:true}).click()
  await expect(page.locator('#course-stage option[value="3"]')).toBeEnabled()
  await complete('Krankenversicherungsbeitrag')
  await leavePage(page)
  await expect(page.locator('.journey-xp')).toContainText('10 XP')
})

test('additional narration downloads deliberately and works after an offline restart',async({page,context})=>{
 test.setTimeout(60_000)
 await visit(page)
 await openPage(page,'Lernkurse')
 await page.getByRole('button',{name:'Kurs öffnen : Lange Wörter sicher behalten',exact:true}).click()
 await page.getByRole('button',{name:'Anhören und ansehen',exact:true}).click()
 const audio=page.locator('.course-media audio')
 const source=await audio.getAttribute('src')
 await expect(page.locator('.course-download')).toHaveCount(1)
 expect(source).toMatch(/^\/course-media\/library\/long-words-de-/)
 expect(await page.evaluate(async(src)=>!!await (await caches.open('anitew-course-audio-v1')).match(src!),source)).toBe(false)
 await page.getByRole('button',{name:'Für offline laden / fortsetzen',exact:true}).click()
 await expect(page.getByText(/Diese Tonspur ist offline verfügbar/)).toBeVisible()
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise<void>(resolve=>navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true}))})
 await context.setOffline(true)
 await page.reload()
 await openPage(page,'Lernkurse')
 await page.getByRole('button',{name:'Kurs öffnen : Lange Wörter sicher behalten',exact:true}).click()
 await expect(page.getByRole('button',{name:'Nur lesen',exact:true})).toBeVisible()
 await expect(page.getByText(/Diese Tonspur ist offline verfügbar/)).toBeVisible()
 await audio.evaluate((element:HTMLAudioElement)=>element.load())
 await expect.poll(()=>audio.evaluate((element:HTMLAudioElement)=>element.seekable.length?element.seekable.end(0):0)).toBeGreaterThan(60)
 await page.getByRole('button',{name:'Offline-Tonspur entfernen',exact:true}).click()
 await expect(page.getByText(/Diese Tonspur braucht noch eine Verbindung/)).toBeVisible()
 expect(await page.evaluate(async(src)=>!!await (await caches.open('anitew-course-audio-v1')).match(src!),source)).toBe(false)
 await context.setOffline(false)
})

test('a different narration language recalls its own word example',async({page})=>{
 await visit(page)
 await openPage(page,'Lernkurse')
 await page.getByRole('button',{name:'Kurs öffnen : Lange Wörter sicher behalten',exact:true}).click()
 await page.getByRole('button',{name:'Anhören und ansehen',exact:true}).click()
 await page.locator('#course-audio-language').selectOption('en')
 await expect(page.locator('#course-audio-language')).toBeEnabled()
 await page.getByRole('button',{name:'Jetzt ohne Vorlage üben',exact:true}).click()
 await page.getByLabel('Deine Antwort',{exact:true}).fill('unpredictability')
 await page.getByRole('button',{name:'Mit der Vorlage vergleichen',exact:true}).click()
 await expect(page.locator('.course-lesson blockquote')).toHaveText('unpredictability')
 await expect(page.locator('.course-lesson blockquote')).toHaveAttribute('lang','en')
})

test('exact wording comparison also helps with private material without saving it',async({page})=>{
 await visit(page)
 await openPage(page,'Lernkurse')
 await page.getByRole('button',{name:'Kurs öffnen : Texte wortgetreu lernen',exact:true}).click()
 await page.getByText('Mit eigenem Material üben',{exact:true}).click()
 await page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)',{exact:true}).fill('Die Wolke zieht weiter.')
 await page.getByLabel('Eigenes Material statt Beispiel verwenden',{exact:true}).check()
 await page.getByRole('button',{name:'Vorlage ausblenden und üben',exact:true}).click()
 await page.getByLabel('Deine Antwort',{exact:true}).fill('Die Wolke fliegt weiter!')
 await page.getByRole('button',{name:'Mit der Vorlage vergleichen',exact:true}).click()
 await expect(page.locator('.course-word-diff')).toContainText('zieht')
 await expect(page.locator('.course-word-diff')).toContainText('fliegt')
 await page.reload()
 await openPage(page,'Lernkurse')
 await page.getByRole('button',{name:'Kurs öffnen : Texte wortgetreu lernen',exact:true}).click()
 await expect(page.getByLabel('Eigener Text oder eigenes Wort (nur für diesen Versuch)',{exact:true})).toHaveValue('')
})
